default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['PGHOST'] %>
  port: <%= ENV['PGPORT'] %>
  database: <%= ENV['PGDATABASE'] %>
  username: <%= ENV['PGUSER'] %>
  password: <%= ENV['PGPASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default
  database: amazon_gift_manager_test

production:
  <<: *default
